api_Handler = Spotify_Handler();

%api_Handler.Request_Auth();
%api_Handler.Request_Auth();
%https://hankhelmers.github.io/CPS_Project/?code=AQDfy4KBf7JeGamdkmOacAw5YE4BLVcCdcHEKXmiZ_j1f1ddkgmn6RwGhCYu8yYzjxthbyJmGmkvjjvQLDRQex9ttDgpi_v-3X05cnTe-kqImALc6WMJkCYoBEOdEYf_TbSrLvjgei41k3Xipv4PUhFkkz_gkUZye19COoE9GyuYw2bUgAGxVd6MHJKh9A
post_auth_url = 'https://hankhelmers.github.io/CPS_Project/?code=AQD5BYYqoz4GZOCU13wmuWp5vCxT-AgYfnbCDkVsCSjgSO_L8iRsyjMAZMTfDwt0eSpptXHRI-_bsSWXPGi0HGgoiNnXojpWF1Vt7U_j3jouc6md3sMWPAVO0pja__L0yKlM4bcKHl0CM0LDoYp-_QU7tU31xa455S1EgYcoNGDme1cJEU-mIirJlJPz8A';

api_Handler.Request_Auth();
post_url = 'https://hankhelmers.github.io/CPS_Project/?code=AQBuKAn8qZqHHabsyKiMlrkGRwUMM2KTMBR5uNa0kW9-CDyPM-16YB4MX7ruOlfoP2hPtly7XZO-Of996Ic3qxoSSw4ntLcc7NhnZXwgK3ghWqM-_2hUuPFjzgyNVtGJssyONHc9Dn7KkoGFNM1MWQWJDWe_Csb6-xOHSuzGFmpNH9LBZLMrwL5iiteUZw'
api_Handler.set_Auth_Code(post_url);